# Use mariadb as base image
FROM mariadb

# Set the working directory to /app
WORKDIR /app

ENV MYSQL_ROOT_PASSWORD=mypass

# Install necessary dependencies for compiling (assuming you need g++)
RUN apt-get update && \
    apt-get install -y \
    g++ \
    make \
    libmysqlcppconn-dev libmysqlcppconn7v5 \
    libcpprest-dev build-essential libssl-dev \
    && rm -rf /var/lib/apt/lists/*

# install gtest (a testing framework for C++ made by Google)
RUN apt-get update && \
    apt-get install -y \
    git cmake\
    && git clone https://github.com/google/googletest.git \
    && cd googletest \
    && mkdir build \
    && cd build \
    && cmake .. \
    && make \
    && make install

EXPOSE 8080 3306