# Use mariadb as base image
FROM mariadb

# Set the working directory to /app
WORKDIR /app

ENV MYSQL_ROOT_PASSWORD=mypass

# Install necessary dependencies for compiling (assuming you need g++)
RUN apt-get update && \
    apt-get install -y \
    g++ \
    make \
    libmysqlcppconn-dev libmysqlcppconn7v5 \
    libcpprest-dev build-essential libssl-dev \
    && rm -rf /var/lib/apt/lists/*

EXPOSE 8080